- grammars/sql.cson
Presently only highlights `is not null`.
> Highlight "is null"

- grammars/sql.cson
According to https://dev.mysql.com/doc/refman/5.5/en/regexp.html REGEXP is a valid SQL keyword. Added it to the SQL grammar
> Added REGEXP support

- grammars/sql.cson
- spec/grammar-spec.coffee
I thought `NOT` was a keyword on its own, but it isn't, so I added `NOT REGEXP` and `NOT RLIKE` as keywords on their own
> `NOT REGEXP` and `NOT RLIKE`

- grammars/sql.cson
- spec/grammar-spec.coffee
As discussed [here](https://github.com/atom/language-sql/pull/23), added decimal highlighting in SQL
> Added decimal highlighting

- grammars/sql.cson
`.psql` seems to be a common PostgreSQL file name extension (my team uses it, WebStorm's most popular SQL plugin uses it). So I've added it to the list of recognized SQL extensions for this plugin.
Adding it ought not to cause collisions with other plugins.
> Add .psql to list of recognized SQL extensions

- grammars/sql.cson
- spec/grammar-spec.coffee
Hi,
I've been using this package for a Databases class I'm taking, and it's proven quite useful (and aesthetically pleasing, naturally). However, I've noticed the package doesn't seem to highlight valid statements like ADD FOREIGN KEY and DROP CONSTRAINT.
Since this is a relatively simple issue to fix, I took the liberty of adding and extending the appropriate grammar rules. Please review my pull request for exactly what was added; I'd be happy to make any changes if need be.
Thanks,
Caleb
> Extend DROP keyword; add ADD keyword

- grammars/sql.cson
.dsql is used by Microsoft when interacting with their APS/PDW products. Same syntax as normal, just a different file extension.
> Added .dsql file extension

- grammars/sql.cson
MySQL comments starting with `#` are not standard and since they mess up syntax with temp tables in T-SQL, I suggest they should be removed from the package.
> Removed MySQL comments

- grammars/sql.cson
USE is used to select a database in SQL Server when a database is connected to.
EXEC and OPENQUERY are both used to get data on other servers.
I have grouped this with the VALUES keyword as EXEC/OPENQUERY are dealing with similar data.
I have also added USE into this dictionart as I felt it is cleaner than adding into dictionary keyword.other.DML.sql but let me know if you disagree.
> Addition of T-SQL syntax: USE, GO, INTO, EXEC, OPENQUERY

- grammars/sql.cson
1. Added highlighting for DECLARE keyword
2. Fixes the highlighting for USE keyword added in previous commit - now highlights correctly.
Fixes #26
> Fixes #26 for highlighting DECLARE

- grammars/sql.cson
- spec/grammar-spec.coffee
Hi,
I recently discovered that the grammar for this package does not tokenize the SQL `UNIQUE` keyword. It's a standard SQL modifier (like `PRIMARY KEY`), so I think it should be tokenized.
I believe I've added everything required (including a passing unit test), but please let me know if you have any concerns or changes to request.
**Before:**
**After:**
Thanks,
Caleb
> Tokenize UNIQUE modifier

- grammars/sql.cson
Adds highlighting for intersect (all) keyword(s).
**Before**:
**After**:
> Add intersect (all) keyword highlighting

- grammars/sql.cson
Hi,
This PR tokenizes the SQL `DEFAULT` modifier:
**Before:**  
**After:**  
I didn't feel any additional tests were necessary, since I assigned this modifier the same classification as the `UNIQUE` modifier (which I already added to the grammar with a test back in #46). All tests are still passing, though. :)
> Tokenize DEFAULT modifier

- grammars/sql.cson
- Highlight `timestamptz` data type
- a data type that's supported by PostgreSQL, Redshift (, also Oracle?)
Improve visibility of `timestamptz` in SQL queries
- before
- after
- none
- none
> Highlight timestamptz type

- grammars/sql.cson
- spec/grammar-spec.coffee
Some SQL dialects (particularly MySQL) support a very handy syntax for dropping and creating conditionally via the `IF NOT EXISTS` and `IF EXISTS` modifiers (respectively).
However, Atom does not currently tokenize these modifiers when used in `CREATE` and `DROP` statements:  
This PR extends the `CREATE` and `DROP` statements to support the `IF NOT EXISTS` and `IF EXISTS` modifiers:  
You'll notice my changes also have the added benefit of making the `CREATE` and `DROP` tokenization a bit more robust (see the `CREATE TABLE;` statement without arguments, as shown above).
To accompany these changes, I've added three new (passing) unit tests, and all existing tests continue to pass. Hooray for unit tests!
Anyway, thanks for considering this; please let me know if I need to make any further …
> Extend CREATE/DROP to support IF EXISTS modifiers

- grammars/sql.cson
Added 'q' to list of file endings to work with.
Could fork into another project.
Lots of teams working with Hadoop, Big Data, and Data Science projects are creating HiveQL scripts. The standard extension for HiveQL is '.q'
Much of HiveQL is nearly ANSI standard, but in essence is a subset. Some specific HiveQL keywords may not be captured/highlighted. Would require further refinement in this package.
None.
> Added .q to list of relevant files (HiveQL)

- grammars/sql.cson
- spec/grammar-spec.coffee
The keywords for `time` and `timestamp` do not appear to work as intended.
This issue is explained in textmate/sql.tmbundle#11 and has been duplicated when the code was converted for Atom.
> These strings are highlighted:
>
>`times(123) withoutstimeszone`
>`timestamps(123) withoutstimeszone`
>
>But it appears that the regular expressions were intended to match "without time zone", intended to make the 's' on timestamp optional, and to make the numeric constant in parentheses optional. As it is, it only works "withoutstimeszone" and the numeric constant must be present to get the time zone string.
This change fixes the issue.
The fix in the Textmate project replaces
`|\b(times)(?:\((\d+)\))(\swithoutstimeszone\b)?`
with
`|\b(times?)\b(?:\((\d+)\))?(\swith(?:out)?\stime\szone\b)?`
and …
> Correct time/timestamp grammar matches

- grammars/sql.cson
Added .hql format to list of known file extentions to handle hive SQL files (.hql). Hive is part of Hadoop and is used for big data applications.
> Added .hql format for Hive SQL (big data) files

- grammars/sql.cson
- spec/grammar-spec.coffee
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
They were overly complicated and causing bugs such as https://github.com/atom/language-php/issues/187.  Simplify them.
None.
Easier to understand, less conflicts with other rules due to the removal of the `^` start-of-line match.
None.
Fixes atom/language-php#187
> Clean up comment regexes

- grammars/sql.cson
- Highlight `float` as a data type
- `float` without precision is supported by Amazon Redshift and Oracle
Improve visibility of timestamptz in SQL queries
- before
- after
> Highlight bare float type

- grammars/sql.cson
- spec/grammar-spec.coffee
- Add highlight for a few conditional expressions: `COALESCE`, `NVL`, and `NULLIF`
- these expressions are available on PostgreSQL, MySQL, Oracle, Amazon Redshift, and more
I hope specs which I added work well 🙏 
Improve visibility of these keywords in SQL queries
> Add highlight of a few conditional expressions (COALESCE, NVL, and NULLIF)

- grammars/sql.cson
- spec/grammar-spec.coffee
- Scoped `()` as `punctuation.definition.section|parameters.bracket.round.begin|end.sql`
- Scoped `,` as `punctuation.separator(.parameters).comma.sql`
- Scoped `.` as `punctuation.separator.period.sql`
- Scoped `;` as `punctuation.terminator.statement.semicolon.sql`
- Rewrote grammar for storage types, added `nchar` and `bit varying`, removed `var char` (with a space, couldn't find any documentation on this type)
- Added specs
Fixes #68
> Tokenize punctuation
